### PR TITLE
Rust rewrite

### PR DESCRIPTION
**Pull request by Deltaphish**
Complete rewrite using rust rocket.
No JS plus transcoded images result in very fast page loads.
Darkmode by default.
pls merge

### CODE REVIEW

**Review by 89netraM — APPROVED** [review]
Very nice

**Review by rosengrenen — DISMISSED** [review]

**Comment by Hoidi** [comment]
Oh rip reviews im sorry

**Review by 89netraM — DISMISSED** [review]
Even better!

**Review by rosengrenen — APPROVED** [review]

**Comment by Portals** [comment]
Please hold on on merging this since there are pictures of people that haven't approved them being uploaded yet.

**Comment by hulthe** [comment]
@Deltaphish Rocket [version 0.5](https://rocket.rs/v0.5-rc/guide/) is around the corner. They recently dropped [0.5-rc1 on crates.io](https://crates.io/crates/rocket/versions) so could be worth it to do the migration now to save some trouble later. There's lots of breaking changes, but for a project this small is should be easy-peasy.

The final release is due this Friday IIRC

**Comment by hulthe** [comment]
Also big :heart: on the no JS

**Comment by Deltaphish** [comment]
All pictures of people, except of those who have given permission on slack, and Elijah Wood, have been replaced by a default avatars. 
After this branch has been merged i will squash master which will completely remove all traces of them (i think).

I have also updated rocket to 0.5.0-rc1, and rust to 1.53 stable which should solve some build issues.
While the rocket version is a release candidate, it  allows us to run the server on stable rust, so I think it balances out.

**Review by hulthe — APPROVED** [review]
LGTM :eggplant:

**Pull request merged**
