### PR TITLE
Replace IRC link with Slack link

### PR DESCRIPTION
**Pull request by hulthe**
irc.chalmers.it is a dead link, and digit only hangs out on the Slack:tm:  anyways

let's all join together and praise our corporate overlords :pray:

### CODE REVIEW

**Review by 89netraM — CHANGES_REQUESTED** [review]
Please also update the [ANSI version](https://github.com/cthit/digit.chalmers.it/blob/872d4cba1747d9e3daf65fbbcf663fdf520fbb19/templates/index.ansi.html.tera#L25)

**Comment by hulthe** [comment]
done :eyes:

**Review by 89netraM — APPROVED** [review]
Super 👍

**Review by Deltaphish — APPROVED** [review]
look goodo

**Pull request merged**
