### PR TITLE
Add more member data

### PR DESCRIPTION
**Pull request by NeonSky**

### CODE REVIEW

**Comment by Hoidi** [comment]
You should probably fix that docker build tho

**Comment by NeonSky** [comment]
@Hoidi That's not a problem with the code. The builds work fine on the previous repo. You just need to update the webhook with DockerHub that this repo uses. I can't do that since I no longer have those permissions. :)

**Comment by NeonSky** [comment]
You should fine it in this repo's settings. Maybe you have to visit DockerHub for something as well.

**Comment by NeonSky** [comment]
Merging as the CI thing is related to repo settings and not the code.

**Pull request merged**
